config/routes.rb
Rails.application.routes.draw do
 
  resources :organization_details
  resources :organizations
  root 'home#index'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
 

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/organization_detail.rb
class OrganizationDetail < ApplicationRecord
	validates :name, presence:true 
	validates :phone, presence:true
	mount_uploader :avatar, ImageUploader
end

app/controllers/organization_details_controller.rb
class OrganizationDetailsController < ApplicationController
  before_action :set_organization_detail, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user!, only: [:index, :new, :show, :edit, :update, :destroy]

  # GET /organization_details
  # GET /organization_details.json
  def index
    @organization_details = OrganizationDetail.all
  end

  # GET /organization_details/1
  # GET /organization_details/1.json
  def show
  end

  # GET /organization_details/new
  def new 
    @organization_detail = OrganizationDetail.new 
  end

  # GET /organization_details/1/edit
  def edit
  end

  # POST /organization_details
  # POST /organization_details.json
  def create
    @organization_detail = OrganizationDetail.new(organization_detail_params)
    respond_to do |format|
      if @organization_detail.save
        format.html { redirect_to @organization_detail, notice: 'Organization detail was successfully created.' }
        format.json { render :show, status: :created, location: @organization_detail }
      else
        format.html { render :new }
        format.json { render json: @organization_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organization_details/1
  # PATCH/PUT /organization_details/1.json
  def update 
    @id =OrganizationDetail.find(params[:id])
    respond_to do |format|
      if @organization_detail.update(organization_detail_params) 
        format.html { redirect_to action:'show', controller: 'organizations', id:@id.organization_id, notice: 'Organization detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization_detail }
      else
        format.html { render :edit }
        format.json { render json: @organization_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organization_details/1
  # DELETE /organization_details/1.json
  def destroy
    @organization_detail.destroy
    respond_to do |format|
      format.html { redirect_to organization_details_url, notice: 'Organization detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization_detail
      @organization_detail = OrganizationDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_detail_params
      params.require(:organization_detail).permit(:name, :phone, :email, :organization_id, :avatar, :remove_avatar, :image_cache)
    end
end

app/helpers/organization_details_helper.rb
module OrganizationDetailsHelper
end

app/views/organization_details/_form.html.erb
<%= form_with(model: organization_detail, local: true) do |form| %>
  <% if organization_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization_detail.errors.count, "error") %> prohibited this organization_detail from being saved:</h2>

      <ul>
      <% organization_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field"> 
    <%= form.label :organization_id %>
    <%= form.collection_select :organization_id, Organization.order(:name), :id, :name, include_blank: true %> 
  </div>

   <%= form.file_field :avatar %>

  <% if organization_detail.avatar? %> 
    <%= image_tag(organization_detail.avatar.url, style: 'width:100px') if organization_detail.avatar? %>
    <div>
      <%= label_tag :remove_avatar do %>
        Remove avatar
        <%= form.check_box :remove_avatar %>
      <% end %>
    </div>
  <% end %>

  <br>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/organization_details/edit.html.erb
<h1>Editing Organization Detail</h1>

<%= render 'form', organization_detail: @organization_detail %>
 
<%= link_to 'Back', url_for(:back) %>

app/views/organization_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organization Details</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organization_details.each do |organization_detail| %>
      <tr>
        <td><%= organization_detail.name %></td>
        <td><%= organization_detail.phone %></td>
        <td><%= organization_detail.email %></td>
        <td><%= link_to 'Show', organization_detail %></td>
        <td><%= link_to 'Edit', edit_organization_detail_path(organization_detail) %></td>
        <td><%= link_to 'Destroy', organization_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization Detail', new_organization_detail_path %>

app/views/organization_details/new.html.erb
<h4>New PIC Organization</h4>

<%= render 'form', organization_detail: @organization_detail %>

<%= link_to 'Back', organization_details_path %>

app/views/organization_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization_detail.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @organization_detail.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @organization_detail.email %>
</p>

<%= link_to 'Edit', edit_organization_detail_path(@organization_detail) %> |
<%= link_to 'Back', organization_details_path %>