config/routes.rb
Rails.application.routes.draw do
 
  resources :organization_details
  resources :organizations
  root 'home#index'

  resources :sessions, only: [:new, :create, :destroy]
  resources :users
 

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/organization.rb
class Organization < ApplicationRecord
	validates :name, presence:true
	validates :email, presence:true, uniqueness:true
	validates :phone, presence:true
	mount_uploader :logo, ImageUploader
	#has_many :organization_details
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user!, only: [:index, :new, :show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization_details = OrganizationDetail.where(organization_id: params[:id]).limit(10)
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :phone, :email, :website, :logo, :remove_logo, :image_cache)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_with(model: organization, local: true) do |form| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website %>
  </div>

   <%= form.file_field :logo %>

   <% if organization.logo? %>
    <%= image_tag(organization.logo.url, style: 'width:100px') if organization.logo? %>
    <div>
      <%= label_tag :remove_logo do %>
        Remove logo
        <%= form.check_box :remove_logo %>
      <% end %>
    </div>
    <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organizations</h1>

<table class="table">
  <thead>
    <tr>
      <th>Logo</th>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td>
          <a href="/Details/<%= organization.id %>">
            <%= image_tag(organization.logo.url, style: 'width:100px') if organization.logo? %>
          </a>
        </td>
        <td><%= organization.name %></td>
        <td><%= organization.phone %></td>
        <td><%= organization.email %></td>
        <td><%= organization.website %></td>
        <td><%= link_to 'Details', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>
 <%= image_tag(@organization.logo.url, style: 'width:100px') if @organization.logo? %>
<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @organization.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @organization.email %>
</p>

<p>
  <strong>Website:</strong>
  <%= @organization.website %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>


<br>
<h3>PIC</h3> 


<table class="table">
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th> 
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @organization_details.each do |organization_detail| %>
      <tr>
        <td> 
            <%= image_tag(organization_detail.avatar.url, style: 'width:100px') if organization_detail.avatar? %> 
        </td>
        <td><%= organization_detail.name %></td>
        <td><%= organization_detail.phone %></td>
        <td><%= organization_detail.email %></td>  
        <td><%= link_to 'Edit', edit_organization_detail_path(organization_detail) %></td>
        <td><%= link_to 'Destroy', organization_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>